server:
  port: 8081

swagger:
  title: Ping API
  description: Ping API that sends a Ping and waits for a Pong
  include: /api/.*

ping:
  jms: true
  rest: true

spring:
  application:
    name: ping
  jpa:
    hibernate:
      ddlAuto: none
  liquibase:
    changeLog: classpath:db/changelog.yml
# injected by config/config-app/src/main/resources/configs/ping-${profile}.yml
#  activemq:
#    brokerUrl: tcp://localhost:61616
# injected by config/config-app/src/main/resources/configs/ping-${profile}.yml
#  datasource:
#    driverClassName: org.h2.Driver
#    url: jdbc:h2:mem:ping;MODE=PostgreSQL
#    username: sa
#    password:

feign:
  hystrix:
    enabled: true

eureka:
# injected by config/config-app/src/main/resources/configs/application-${profile}.yml
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/