server:
  port: 8081

swagger:
  title: Ping API
  description: Ping API that sends a Ping and waits for a Pong
  include: /api/.*

ping:
  rest: true
  servicebus: true
  eventhub: true

cluster:
  enabled: true
  group: ${spring.application.name}:${spring.profiles.active}
  instance: ${spring.application.name}:${spring.profiles.active}:${spring.application.instance_id:${random.value}}

spring:
  application:
    name: ping
  jpa:
    hibernate:
      ddlAuto: none
  liquibase:
    changeLog: classpath:db/changelog.yml
  cloud:
    azure:
      credential-file-path: classpath:authentication.json
      resource-group: tsivb-srv
      region: Central US
      eventhub:
        namespace: tsivb-eventhub
        checkpoint-storage-account: tsivbeventhubstorage
      servicebus:
        queue:
          enabled: false
        topic:
          enabled: false
      telemetry:
        enabled: false
      redis:
        enabled: false
    stream:
      bindings:
        ping:
          destination: ping
          group: $Default
        pong:
          destination: pong
          group: $Default
# injected by vault or pipeline
#  datasource:
#    driverClassName: org.h2.Driver
#    url: jdbc:h2:mem:ping;MODE=PostgreSQL
#    username: sa
#    password:


feign:
  hystrix:
    enabled: true

eureka:
# injected by vault or pipeline
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/

azure:
# injected by vault or pipeline
#  servicebus:
#    connection: none