server:
  port: 8081

swagger:
  title: Ping API
  description: Ping API that sends a Ping and waits for a Pong
  include: /api/.*

ping:
  rest: true
  servicebus: true

spring:
  application:
    name: ping
  jpa:
    hibernate:
      ddlAuto: none
  liquibase:
    changeLog: classpath:db/changelog.yml
# injected by vault or pipeline
#  datasource:
#    driverClassName: org.h2.Driver
#    url: jdbc:h2:mem:ping;MODE=PostgreSQL
#    username: sa
#    password:

feign:
  hystrix:
    enabled: true

eureka:
# injected by vault or pipeline
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/

azure:
# injected by vault or pipeline
#  servicebus:
#    connection: none